apiVersion: apps/v1
kind: Deployment
metadata:
  name: BM
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bm-deploy
  template:
    metadata:
      labels:
        app: bm-deploy
    spec:
      containers:
        - name: bm-image
          image: hatem95/bm-image:latest
          ports:
            - containerPort: 8080
