apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bm-ingress
spec:
  rules:
    - host: your-bm.com
      http:
        paths:
          - backend:
              service:
                name: bm-service
                port: 80

