name: Build Docker Image

on: [push]

#needs: [lint, test]
jobs:

  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./DockerFile.dockerfile
          push: true
          tags: hatem95/bm-image:v1.0

  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run:
          echo "Workflow complete!"