name: build_and_push_docker_image
on:
  workflow_run:
    workflows: ["code_analysis_and_test"]
    types:
      - completed
    result: success
jobs:

  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code # checks out the repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub #Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image #build and push docker image
        uses: docker/build-push-action@v2
        with:
          file: ./DockerFile.dockerfile #dockerfile path
          push: true # true to push the image
          tags: |
              hatem95/bm-image:${{ github.sha }}
              hatem95/bm-image:latest 
