name: lint,test&Sonar

on: [push]

jobs:

  lint:

    runs-on: ubuntu-latest # The job runs on an Ubuntu machine

    steps:
      - name: Checkout code # checks out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 11  #java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: change permission #change script permission
        run:  chmod +x gradlew

      - name: Build with Gradle #build the code
        run: ./gradlew build

      - name: PMD Lint
        uses: pmd/pmd-github-action@v1.4.0
        with:
            rulesets: 'pmd-rules.xml' #user PMD rules xml file
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Make Gradlew Executable # change permission to make script executable
        run:  chmod +x gradlew
      - name: Run Unit Tests  # Test stage
        run: ./gradlew test

  Sonar:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
              java-version: 11
              distribution: 'adopt'

      - name: Build and analyze
        env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Make Gradlew Executable # change permission to make script executable
        run: chmod +x gradlew
        
      - name: sonar run
        run: ./gradlew build sonar --info