name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build with Gradle
        run: ./spring-boot-app/gradlew build
      - name: Run Checkstyle
        run: ./spring-boot-app/gradlew checkstyleMain

