name: Deploy to AKS

on:
    push:
      branches:
        - main

jobs:
    deploy:
      runs-on: ubuntu-latest
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      steps:

        - name: Install kubectl
          run: |
            az aks install-cli

        - name: Set Kubeconfig
          run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yaml

        - name: Deploy to AKS
          run: |
            kubectl apply -f kubernetes/deployment.yaml
            kubectl apply -f kubernetes/service.yaml
            kubectl set image deployment/your-deployment-name your-container-name=your-dockerhub-username/your-image-name:latest
            kubectl rollout restart deployment/your-deployment-name
          env:
            KUBECONFIG: kubeconfig.yaml
