name: lint,test&Sonar

on: [push]

jobs:

  lint:

    runs-on: ubuntu-latest # The job runs on an Ubuntu machine

    steps:
      - name: Checkout code # checks out the repository
        uses: actions/checkout@v2

      - name: Make Gradlew Executable # change permission to make script executable
        run: chmod +x gradlew

      - name: Build with Gradle project #Build the project
        run: ./gradlew build

      - name: Run Checkstyle
        uses: checkstyle/checkstyle-action@v2
        with:
          config: ./config/checkstyle/checkstyle.xml
          checkstyle_version: 8.45
          source_files: 'src/**/*.java'
          output_file: ./checkstyle-result.xml
      #- name: Run Checkstyle   #Lint stage using checkstyle
      #   run: ./gradlew checkstyleMain

  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Make Gradlew Executable # change permission to make script executable
        run:  chmod +x gradlew
      - name: Run Unit Tests  # Test stage
        run: ./gradlew test

  #Sonar:
      #runs-on: ubuntu-latest
      #steps:
      #- name: Checkout code
      #  uses: actions/checkout@v2
      #- name: SonarQube Scan
       # uses: sonar-source/sonarqube-scan-action@v1
        #with:
        #projectBaseDir: ./project-dir
        #projectName: "My Project"
        #projectKey: "my-project-key"
        #serverUrl: "http://sonarqube-server-url"
        #token: ${{ secrets.SONARQUBE_TOKEN }}
