name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Make Gradlew Executable
        run: chmod +x spring-boot-app/gradlew
      - name: Build with Gradle project
        run: ./spring-boot-app/gradlew build
      - name: Run Checkstyle
        run: ./spring-boot-app/gradlew checkstyleMain

