name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Make Gradlew Executable
        run: chmod +x gradlew
      - name: Build with Gradle project
        run: ./gradlew build
      - name: Run Checkstyle   #Lint stage
        run: ./gradlew checkstyleMain
      - name: Run Unit Tests  # Test stage
        run: ./gradlew test --no-daemon
