name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
            java-version: 11
            distribution: 'adopt'

      - name: Make Gradlew Executable
        run: chmod +x gradlew
      - name: Build with Gradle project #Build the project
        run: ./gradlew build

      #- name: Run Checkstyle   #Lint stage
        #run: ./gradlew checkstyleMain

      - name: Run Unit Tests  # Test stage
        run: ./gradlew test --no-daemon

      #- name: SonarQube Scan
       # uses: sonar-source/sonarqube-scan-action@v1
        #with:
        #projectBaseDir: ./project-dir
        #projectName: "My Project"
        #projectKey: "my-project-key"
        #serverUrl: "http://sonarqube-server-url"
        #token: ${{ secrets.SONARQUBE_TOKEN }}
